services:
  bot:
    build:
      context: .
    ports:
      - 8000:8000
    container_name: telegram_bot
    restart: unless-stopped
    environment:
      - TOKEN=${TOKEN}
    volumes:
      - .:/app
      - .:/bot.db
volumes:
  db_data:
