version: '3.8'

services:
  bot:
    build: .
    container_name: telegram_bot
    restart: unless-stopped
    environment:
      - TOKEN=${TOKEN}  # Токен бота из .env
    volumes:
      - .:/app  # Монтируем текущую директорию в контейнер